Updated Scripts in Darwin

diff --git a/OS X/Custom-Git-Commands/git-catchup b/OS X/Custom-Git-Commands/git-catchup
--- a/OS X/Custom-Git-Commands/git-catchup
+++ b/OS X/Custom-Git-Commands/git-catchup
@@ -1,5 +1,24 @@
 #! /usr/bin/env sh
 
-_branch=${1:-`git current-branch`}
+while getopts ":r:" opt; do
+  case $opt in
+    r)
+      REMOTE=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
-git log $_branch..origin/$_branch
+shift $((OPTIND-1))
+
+REMOTE=${REMOTE:-origin}
+BRANCH=${1:-`git current-branch`}
+
+git log $BRANCH..$REMOTE/$BRANCH
